### ISSUE TITLE
Using array_key_exists() on objects is deprecated

### ISSUE THREAD

**Issue by punkerisaacs** [Paybook/sync-php#3]
"if (array_key_exists('token', $session))"  replace with  "if (isset($session->token))" to fix them

**Comment by aldoea** [comment]
Ey @punkerisaacs49 thank you very much, I'll make the change rigth now!

**Comment by aldoea** [comment]
@punkerisaacs49 `v1.0.2` released on packagist.org https://packagist.org/packages/paybook/sync-php , could you try it please? Thank you!
Source: https://www.php.net/manual/en/migration74.deprecated.php

**Comment by punkerisaacs49** [comment]
yes it works!! thanks!! 👍  @aldoea

**Comment by punkerisaacs** [comment]
yes it works!! thanks!!
